# Generated by Django 5.1.5 on 2025-01-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opes', '0002_alter_client_email_alter_client_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
