# Generated by Django 5.1.5 on 2025-01-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opes', '0003_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
